# Generated by Django 5.0.1 on 2024-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='O9Cx1ObWi3lP', editable=False, max_length=12, unique=True),
        ),
    ]
