# Generated by Django 5.0.1 on 2024-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0003_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default=580215839730, editable=False, max_length=12, unique=True),
        ),
    ]
